version: '3'
services:
  bullboard:
    image: "serebano/bullboard"
    ports: 
      - ${PORT}:${PORT}
    environment: 
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_TLS: ${REDIS_TLS}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      QUEUES: ${QUEUES}
      PORT: ${PORT}